
export const ROUTE_CONSTANT = Object.freeze({
  addEmployee: 'staff-management/add-staff',
  applyLeave: 'apply-for-leave',
  attendance: 'attendance',
  employeeDetails: 'employee-details',
  policies: 'policies',
  dashboard: 'dashboard',
  staffManagement: 'staff-management',
  leaveManagement: 'leave-management',
  leaveApply: 'leave-apply',
  applicationStatus: 'leave-confirmation-page',
  attendanceDetails: 'attendance/attendance-details',
  profileDetails: 'profile-details',
  staffRegistration: 'staff-registration',
  leaveConfirmationPage: 'leave-confirmation-page',
  changePassword : 'change-password',
  login: 'login',
  forgotPassword: 'forgot-password',
  otp: 'otp',
});